---
name: Check stuff

"on":
  pull_request:
    branches:
      - "*"

jobs:
  mainjob:
    runs-on: ubuntu:latest
    steps:
      - name: write
        id: var-write
        run: |
          echo "var=value" >> $GITHUB_OUTPUT

      - name: read
        id: var-read
        run: |
          echo "Var value:"
          echo "${{ steps.var-write.outputs.var }}"
